version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.44-stretch-node
    steps:
      - checkout
      - restore_cache:
          key: v1-rust-cache-{{ .Branch }}-
      - run:
          name: Build and test
          command: |
            echo $CARGO_HOME
            rustup component add rustfmt
            cargo install cargo-audit
            cargo fmt -- --check
            cargo audit
            cargo build
            cargo test
      - run:
          name: Release build
          command: >
            OPENSSL_STATIC=1 OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu OPENSSL_INCLUDE_DIR=/usr/include/openssl
            cargo build --release
      - run:
          name: Stage files
          command: |
            mkdir dist
            cp -a ./target/release/web-settings dist/app
            cp -a ./templates dist
            cp -a ./locales dist
      - persist_to_workspace:
          root: .
          paths:
            - dist
      - save_cache:
          key: v1-rust-cache-{{ .Branch }}-{{ checksum "Cargo.lock" }}
          paths:
            - "/usr/local/cargo/registry"
            - "./target"
  deploy:
    docker:
      - image: circleci/rust:1.44-stretch-node
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "45:16:fd:9e:94:b8:84:59:ae:5b:50:6e:e7:e2:e5:09"
      - run:
          name: Add fingerprint
          command: echo $UPDATE_FINGERPRINT >> ~/.ssh/known_hosts
      - run:
          name: Deploy
          command: |
            sudo apt-get update -y
            sudo apt-get install -y rsync
            ls -lR ./dist
            rsync -v --recursive --delete-after --delay-updates ./dist/ $HOSTNAME:$APP_PATH
            ssh $HOSTNAME sudo /bin/systemctl restart "web-settings"
  mirror:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "19:db:1c:7a:53:a2:a6:7f:c4:3b:9b:57:de:5a:ee:d6"
      - run:
          name: GitHub mirror
          command: |
            git remote add github git@github.com:technic/web-settings.git
            git push --mirror github

workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      # - mirror:
      #     filters:
      #       branches:
      #         only:
      #           - master
